#debug: true
server:
  credentials:
    - list1:
      - key1:
        username: root
        password: rootpass
      - key2:
        username: root
        password: rootpass
    - list2:
      - key21:
        username: root
        password: rootpass
      - key22:
        username: root
        password: rootpass
  users: 
    root:
      username: root
      password: rootpass
    guest:
      username: guest
      password: guestpass